import numpy as np 
a=np.ones((2,3))
print(a)
b = np.ones(5, dtype=int)
print(b)
c=np.full((3,3),7)
print(c)
d=np.full((2,2),6)
print(d)
e=np.empty((5,6))
print(e)
f=np.empty((3,4))
f.fill(6)
print(f)
